<a href="https://colab.research.google.com/github/ShashwatVv/naiveDL/blob/main/Torch_Basics_revision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch as tch
import numpy as np

In [3]:
##see if the environment is  activated
torch.__version__

'1.10.0+cu111'

In [7]:
a = [1,2,3]
a = np.array(a)
a.dtype

dtype('int64')

In [10]:
b = tch.tensor(a)

In [11]:
b.dtype

torch.int64

In [12]:
c = tch.from_numpy(a)

In [13]:
c.dtype

torch.int64

In [14]:
print(b)
print(c)

tensor([1, 2, 3])
tensor([1, 2, 3])


Conclusion --> `torch.tensor(X)` and `torch.from_numpy(X)`, both convert numpy array X to a tensor





In [20]:
## torch.as_tensor
b = np.array([1,2,3])
a = [1,2,3]
c = tch.as_tensor(a)
d = tch.from_numpy(b)

Conclusion --> as_tensor : A more generic version



In [25]:
### relationship between original numpy_array and  torch.from_numpy

a = [1,2,3,4]
b = np.array(a)
c = tch.as_tensor(a)
d = tch.tensor(b)
e = tch.from_numpy(b)
print('before')
print(a)
print(b)
print(c)
print(d)
print(e)
a[1]=55
b[1] =44 ##numpy array changed here
print('after')
print(a)
print(b)##numpy array changed
print(c)
print(d)
print(e)##tensor created from that numpy array has also changed, due to a direct link 

before
[1, 2, 3, 4]
[1 2 3 4]
tensor([1, 2, 3, 4])
tensor([1, 2, 3, 4])
tensor([1, 2, 3, 4])
after
[1, 55, 3, 4]
[ 1 44  3  4]
tensor([1, 2, 3, 4])
tensor([1, 2, 3, 4])
tensor([ 1, 44,  3,  4])


In [26]:
###use torch.tensor(X) as it creates a copy of X 

Difference between torch.tensor and torch.Tesnor [capital 'T']

In [30]:
a = np.array([1,2,3])
b = tch.tensor(a)
c = tch.Tensor(a)
## torch.Tensor has default data type as Float
print(b)
print(c)

tensor([1, 2, 3])
tensor([1., 2., 3.])


Create our  own tesnor

In [32]:
size = 2,2
tch.empty(size)

tensor([[-2.3635e-09,  3.0901e-41],
        [ 3.3631e-44,  0.0000e+00]])

In [40]:
tch.zeros(4,2)
#torch.ones()
#torch.arange()
#torch.linspace()
#torch.reshape()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [45]:
print(tch.rand(3,4))
print(tch.randn(3,4))##normal

tensor([[0.8267, 0.7517, 0.3449, 0.5151],
        [0.8734, 0.8697, 0.3100, 0.3814],
        [0.2152, 0.8699, 0.6739, 0.4664]])
tensor([[-1.2810,  0.5937,  1.4360, -0.8516],
        [-0.7639,  1.0355, -0.9883, -0.4442],
        [ 1.3773, -0.5010,  1.7380, -1.0412]])
