<a href="https://colab.research.google.com/github/ShashwatVv/naiveDL/blob/main/Torch_Basics_revision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch as tch
import numpy as np

In [3]:
##see if the environment is  activated
torch.__version__

'1.10.0+cu111'

In [7]:
a = [1,2,3]
a = np.array(a)
a.dtype

dtype('int64')

In [10]:
b = tch.tensor(a)

In [11]:
b.dtype

torch.int64

In [12]:
c = tch.from_numpy(a)

In [13]:
c.dtype

torch.int64

In [14]:
print(b)
print(c)

tensor([1, 2, 3])
tensor([1, 2, 3])


Conclusion --> `torch.tensor(X)` and `torch.from_numpy(X)`, both convert numpy array X to a tensor





In [20]:
## torch.as_tensor
b = np.array([1,2,3])
a = [1,2,3]
c = tch.as_tensor(a)
d = tch.from_numpy(b)

Conclusion --> as_tensor : A more generic version



In [25]:
### relationship between original numpy_array and  torch.from_numpy

a = [1,2,3,4]
b = np.array(a)
c = tch.as_tensor(a)
d = tch.tensor(b)
e = tch.from_numpy(b)
print('before')
print(a)
print(b)
print(c)
print(d)
print(e)
a[1]=55
b[1] =44 ##numpy array changed here
print('after')
print(a)
print(b)##numpy array changed
print(c)
print(d)
print(e)##tensor created from that numpy array has also changed, due to a direct link 

before
[1, 2, 3, 4]
[1 2 3 4]
tensor([1, 2, 3, 4])
tensor([1, 2, 3, 4])
tensor([1, 2, 3, 4])
after
[1, 55, 3, 4]
[ 1 44  3  4]
tensor([1, 2, 3, 4])
tensor([1, 2, 3, 4])
tensor([ 1, 44,  3,  4])
